### PR TITLE
Feature/facebook

### PR DESCRIPTION
**Pull request by bnd5k**
This PR addresses this issue: https://github.com/RagtagOpen/mustachify/issues/21

Here's what it does:

* Adds a simple way to share on FB.  We're using FB sharer, which I found out will share many URLs, but not URLs to images. :/  This PR simply shares the root URL for the mustachify app.  I've set it to the Heroku app's URL for local development. We'll need to set the variable in the Heroku environment too.  I'm not sure if we'd want the mustachify app's URL or the page where it'll ultimately be displayed ( Randy Bryce's site).  For now, I think we can just set it to the Heroku app's URL

* Adds styling for social sharing buttons. I attempted to keep the implementation independent from other CSS in the app so that if we need the same functionality in other Ragtag projects, we can just copy this or turn it into a shareable library.

image

### CODE REVIEW

**Comment by jillh510** [comment]
Ugh, I notice twitter is sharing the result page where it should be either uploading the image and sharing it, or sharing the same "stache yourself" page that Facebook shares. Can you add that to this PR?

**Comment by jillh510** [comment]
Also, the buttons are awfully big: 
screen shot 2018-02-24 at 12 09 06 pm

**Comment by bnd5k** [comment]
I pushed an update for the twitter shareable URL.  We'll just share the URL to the mustachify app for now.

I added some text and a twitter handle for ragtag.  It's just placeholder stuff and we can change it to whatever the campaign wants.

**Comment by bnd5k** [comment]
I reduced the size of the share buttons, but I'm not sure if I've arrived at a good place or if I should continue to shrink them.

It's hard to know what to do with out knowing what the final layout will be.   If the result page is only going to contain a photo, then maybe these share buttons are correctly sized.  If there's going to be a campaign donation or sign up form on the side of the photo, then let me know and I can scale back on the photo size and button size.  LMK.


image

**Pull request merged**
